CC = i586-mingw32msvc-cc
CXX = i586-mingw32msvc-c++
AR  = i586-mingw32msvc-ar
PLATFORM = win32
CXXFLAGS += -D_WIN32_

include Makefile.common

VPATH += src test
LDLIBS += -lws2_32
RANLIB = i586-mingw32msvc-ranlib

test-timer: test-timer.o libwait.a

libwait.a: $(OBJECTS)
	$(AR) crv libwait.a $(OBJECTS)
	$(RANLIB) libwait.a

clean:
	del /Q $(OBJECTS)
